version: '3.8'

services:
  calculator-mcp:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: calculator-mcp-server
    ports:
      - "8080:8080"
    environment:
      - PYTHONPATH=/app
      - MCP_SERVER_NAME=calculator-mcp
      - MCP_SERVER_VERSION=1.0.0
      - DEFAULT_PRECISION=20
      - PYTHONUNBUFFERED=1
    volumes:
      # Volumen para ejemplos (solo lectura)
      - ./examples:/app/examples:ro
      # Volumen para logs persistentes
      - calculator-logs:/app/logs
    restart: unless-stopped
    
    # Healthcheck para monitoreo
    healthcheck:
      test: ["CMD", "python", "-c", "import subprocess; subprocess.run(['bc', '--version'], check=True)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    # Configuraciones de seguridad
    security_opt:
      - no-new-privileges:true
    
    # Sistema de archivos de solo lectura con excepciones
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
      - /app/logs:size=50m
    
    # Límites de recursos
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    
    # Configuración de logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Red personalizada
    networks:
      - calculator-network

  # Servicio opcional: Monitor de métricas
  calculator-monitor:
    image: prom/prometheus:latest
    container_name: calculator-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    restart: unless-stopped
    networks:
      - calculator-network
    depends_on:
      - calculator-mcp

  # Servicio opcional: Dashboard de métricas
  calculator-grafana:
    image: grafana/grafana:latest
    container_name: calculator-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources:ro
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    networks:
      - calculator-network
    depends_on:
      - calculator-monitor

volumes:
  calculator-logs:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

networks:
  calculator-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16